provider "proxmox" {
  endpoint = var.proxmox_api_url
  username = var.proxmox_user
  password = var.proxmox_password
  insecure = var.proxmox_insecure

  # Used to import the Talos image (content_type = "iso") into VM disks
  # (file_id path runs `pvesm path` + `qm disk import` on the node).
  ssh {
    agent        = true
    agent_socket = var.proxmox_ssh_agent_socket
    username     = var.proxmox_ssh_username
  }
}

# Helm provider is configured with the kubeconfig generated by the bootstrap
# module (local_sensitive_file.kubeconfig), so apply order is guaranteed even
# though the provider config references a resource attribute.
provider "helm" {
  kubernetes = {
    config_path = local_sensitive_file.kubeconfig.filename
  }
}

# Kubernetes provider (same kubeconfig) used by the CAPI module to create the
# provider variables Secret consumed by the Cluster API Operator.
provider "kubernetes" {
  config_path = local_sensitive_file.kubeconfig.filename
}
