#!/usr/bin/env bash
#
# export-kubeconfig.sh - export the cluster kubeconfig (and optionally the
# talosconfig) from the applied OpenTofu state, defaulting the Kubernetes API
# `server` to the HAProxy load-balancer address in front of the control plane,
# and optionally install it on a remote host so kubectl/talosctl work from there.
#
# Defaults:
#   endpoint   https://192.168.15.113:6443 (load balancer; cert SAN already present)
#   local path <repo>/kubeconfig.yaml
#   remote     ~/.kube/config (only with --host)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

ENDPOINT="https://192.168.15.113:6443"
OUTPUT_PATH="${REPO_ROOT}/kubeconfig.yaml"
HOST=""
REMOTE_PATH="~/.kube/config"
INSTALL_LOCAL=""
LOCAL_PATH="${HOME}/.kube/config"
EXPORT_TALOS=""
AS_GENERATED=""
TMP_KUBECONFIG=""
TMP_TALOS=""

usage() {
  cat <<'EOF'
Usage: export-kubeconfig.sh [options]

Export the Kubernetes kubeconfig (and optionally the talosconfig) from the
applied OpenTofu state, defaulting the API server to the load balancer in front
of the control plane. Can also install the config on a remote host.

Options:
  --endpoint <url>      API server endpoint written into the kubeconfig.
                        Default: https://192.168.15.113:6443
  --as-generated        Keep the server address Talos generated (first
                        control-plane IP); do not rewrite it.
  --output <path>       Local output path for the kubeconfig.
                        Default: <repo>/kubeconfig.yaml
  --local               Also install the kubeconfig into $HOME/.kube/config,
                        backing up an existing file to $HOME/.kube/config.bak
                        before overwriting.
  --host <user@host>    Also install the kubeconfig on a remote host.
  --remote-path <path>  Remote destination path (default: ~/.kube/config).
  --talos               Also export the talosconfig (local ./talosconfig and,
                        with --host, remote ~/.talos/config).
  -h, --help            Show this help.
EOF
}

cleanup() {
  if [[ -n "$TMP_KUBECONFIG" ]]; then rm -f "$TMP_KUBECONFIG"; fi
  if [[ -n "$TMP_TALOS" ]]; then rm -f "$TMP_TALOS"; fi
}
trap cleanup EXIT

while [[ $# -gt 0 ]]; do
  case "$1" in
    --endpoint)     ENDPOINT="$2"; shift 2 ;;
    --output)       OUTPUT_PATH="$2"; shift 2 ;;
    --local)        INSTALL_LOCAL=1; shift ;;
    --host)         HOST="$2"; shift 2 ;;
    --remote-path)  REMOTE_PATH="$2"; shift 2 ;;
    --talos)        EXPORT_TALOS=1; shift ;;
    --as-generated) AS_GENERATED=1; shift ;;
    -h|--help)      usage; exit 0 ;;
    *) echo "error: unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

command -v tofu >/dev/null 2>&1 \
  || { echo "error: 'tofu' not found in PATH" >&2; exit 1; }

# Read a sensitive raw output from the state; fails with a friendly message if
# the state is empty (cluster not applied yet).
export_raw() {
  local name="$1"
  local value
  value="$(cd "$REPO_ROOT" && tofu output -raw "$name")" || {
    echo "error: cannot read OpenTofu output '$name' (run 'tofu apply' first?)" >&2
    exit 1
  }
  if [[ -z "$value" ]]; then
    echo "error: OpenTofu output '$name' is empty (run 'tofu apply' first?)" >&2
    exit 1
  fi
  printf '%s\n' "$value"
}

install_remote() {
  local path="$1"
  local file="$2"
  echo "  -> installed ${HOST}:${path}"
  # Path is inserted unquoted so the remote shell expands a leading tilde.
  ssh "$HOST" "umask 077; mkdir -p \$(dirname $path); cat > $path && chmod 600 $path" < "$file"
}

TMP_KUBECONFIG="$(mktemp)"
export_raw kubeconfig_raw > "$TMP_KUBECONFIG"

if [[ -n "$AS_GENERATED" ]]; then
  echo "endpoint: (as generated by Talos)"
else
  sed -i -E "s#^([[:space:]]*server:[[:space:]]*).*#\1${ENDPOINT}#" "$TMP_KUBECONFIG"
  echo "endpoint: ${ENDPOINT}"
fi

mkdir -p "$(dirname "$OUTPUT_PATH")"
install -m 600 "$TMP_KUBECONFIG" "$OUTPUT_PATH"
echo "kubeconfig: ${OUTPUT_PATH}"

if [[ -n "$INSTALL_LOCAL" ]]; then
  mkdir -p "$(dirname "$LOCAL_PATH")"
  if [[ -e "$LOCAL_PATH" ]]; then
    cp -p "$LOCAL_PATH" "${LOCAL_PATH}.bak"
    echo "kubeconfig: ${LOCAL_PATH} (previous file kept at ${LOCAL_PATH}.bak)"
  else
    echo "kubeconfig: ${LOCAL_PATH}"
  fi
  install -m 600 "$TMP_KUBECONFIG" "$LOCAL_PATH"
fi

if [[ -n "$HOST" ]]; then
  install_remote "$REMOTE_PATH" "$TMP_KUBECONFIG"
fi

if [[ -n "$EXPORT_TALOS" ]]; then
  TMP_TALOS="$(mktemp)"
  export_raw talos_config > "$TMP_TALOS"
  install -m 600 "$TMP_TALOS" "${REPO_ROOT}/talosconfig"
  echo "talosconfig: ${REPO_ROOT}/talosconfig"
  if [[ -n "$HOST" ]]; then
    install_remote "~/.talos/config" "$TMP_TALOS"
  fi
fi